Improve args handling

diff --git a/linux-config b/linux-config
--- a/linux-config
+++ b/linux-config
@@ -3,69 +3,51 @@
 help()
 {
     echo "Usage: $0 [-a SCRIPT_ACTION] [-d LINUX_DISTRO]"
-    return 1
+    return 0
 }
 
-if test -z $1
-then
-    help
-    exit 1
-fi
+for f in $(find . -maxdepth 2 -name setup.sh -type f)
+do
+    if test ! -x "$f"
+    then
+        echo "Setting script file $f as executable"
+        chmod +x -v "$f"
+    fi
+done
 
-while getopts 'a:d:' arg
+test -z "$1" && help
+
+while getopts 'a:d:h' arg
 do
     case "${arg}" in
-        a) export SCRIPT_ACTION="$OPTARG";;
-        d) export LINUX_DISTRO="$OPTARG";;
-        *) exit 1;;
+        a) SCRIPT_ACTION="$OPTARG";;
+        d) LINUX_DISTRO="$OPTARG";;
+        h) help;;
+        *) help && exit 1;;
     esac
 done
 
-case "$LINUX_DISTRO" in
-    arch|archlinux)
-        shift
-        case "${SCRIPT_ACTION}" in
-            setup-secure-boot)  LINUX_DISTRO=$LINUX_DISTRO sh tools/setup.sh;;
-            install-tkg-kernel) LINUX_DISTRO=$LINUX_DISTRO sh kernels/setup.sh;;
-            setup-rootfs)       LINUX_DISTRO=$LINUX_DISTRO sh rootfs/setup.sh;;
-            setup-services)     LINUX_DISTRO=$LINUX_DISTRO sh tools/setup-services.sh;;
-            install-packages)   LINUX_DISTRO=$LINUX_DISTRO sh packages/setup.sh;;
-            *)
-                if test ! -z "${SCRIPT_ACTION}"
-                then
-                    echo "error: $1: unknown action"
-                    exit 1
-                else
-                    echo "error: $1: invalid action"
-                    exit 1
-                fi
-            ;;
-        esac
-    ;;
-    debian)
-        shift
-        case "${SCRIPT_ACTION}" in
-            setup-secure-boot)  LINUX_DISTRO=$LINUX_DISTRO sh tools/setup.sh;;
-            setup-rootfs)       LINUX_DISTRO=$LINUX_DISTRO sh rootfs/setup.sh;;
-            setup-services)     LINUX_DISTRO=$LINUX_DISTRO sh tools/setup-services.sh;;
-            install-packages)   LINUX_DISTRO=$LINUX_DISTRO sh packages/setup.sh;;
-            *)
-                if test ! -z "${SCRIPT_ACTION}"
-                then
-                    echo "error: $1: unknown action"
-                    exit 1
-                else
-                    echo "error: $1: invalid action"
-                    exit 1
-                fi
-        esac
-    ;;
+if test -z "${SCRIPT_ACTION}"
+then
+    echo "Nothing to do"
+    exit 1
+elif test -z "${LINUX_DISTRO}"
+then
+    echo "No distro was specified"
+    exit 1
+fi
+
+case "${SCRIPT_ACTION}" in
+    setup-secure-boot)  "${SHELL}" -c "LINUX_DISTRO=${LINUX_DISTRO} ./tools/setup.sh";;
+    install-tkg-kernel) "${SHELL}" -c "LINUX_DISTRO=${LINUX_DISTRO} ./kernels/setup.sh";;
+    setup-rootfs)       "${SHELL}" -c "LINUX_DISTRO=${LINUX_DISTRO} ./rootfs/setup.sh";;
+    setup-services)     "${SHELL}" -c "LINUX_DISTRO=${LINUX_DISTRO} ./tools/setup-services.sh";;
+    install-packages)   "${SHELL}" -c "LINUX_DISTRO=${LINUX_DISTRO} ./packages/setup.sh";;
     *)
-        if test ! -z $LINUX_DISTRO
+        if test ! -z "${SCRIPT_ACTION}"
         then
-            echo "error: $LINUX_DISTRO: unknown distribution" && exit 1
-        else
-            echo "error: no distribution was specified" && exit 1
+            echo "error: $SCRIPT_ACTION: unknown action"
+            exit 1
         fi
     ;;
 esac
