fix indentation and sanitize a bit of the code

diff --git a/modules/rootfs/usr/local/bin/git-optimize-repo b/modules/rootfs/usr/local/bin/git-optimize-repo
--- a/modules/rootfs/usr/local/bin/git-optimize-repo
+++ b/modules/rootfs/usr/local/bin/git-optimize-repo
@@ -3,8 +3,8 @@
 while getopts "d:" arg
 do
     case "$arg" in
-        d) repo_dir="${OPTARG}"; break;;
-	?) test ! -z $arg && echo "$arg: invalid argument" && exit 1;;
+        'd') repo_dir="${OPTARG}"; break;;
+	    ?) test ! -z $arg && echo "$arg: invalid argument" && exit 1;;
     esac
 done
 
@@ -14,7 +14,7 @@ then
     git repack -a -d -f --depth=250 --window=250
 else
     previous_dir="$(pwd)"
-    cd "${repo_dir}" && \
-        git repack -a -d -f --depth=250 --window=250 && \
-        cd "${previous_dir}"
+    cd "${repo_dir}"
+    git repack -a -d -f --depth=250 --window=250
+    cd "${previous_dir}"
 fi
